/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const GET: typeof import('../index')['GET']
  const POST: typeof import('../index')['POST']
  const add: typeof import('../utils/add')['add']
  const app: typeof import('../app')['default']
  const axios: typeof import('../utils/request')['axios']
  const node: typeof import('../node')['default']
  const request: typeof import('../utils/request')['default']
  const runtime: typeof import('../index')['runtime']
}
